services:
  web:
    build:
      context: .
      dockerfile: ./docker/production/nginx/Dockerfile
    container_name: dashboard_web
    restart: unless-stopped
    volumes:
      - storage-production:/var/www/storage:ro
    networks:
      - dashboard
      - proxy-net
    depends_on:
      - php-fpm

  php-fpm:
    build:
      context: .
      dockerfile: ./docker/production/php-fpm/Dockerfile
      target: production
    container_name: dashboard_php-fpm
    restart: unless-stopped
    volumes:
      - storage-production:/var/www/storage
    env_file:
      - .env
    networks:
      - dashboard
    depends_on:
      - db

  queue:
    build:
      context: .
      dockerfile: ./docker/production/php-fpm/Dockerfile
      target: production
    container_name: dashboard_queue
    restart: unless-stopped
    depends_on:
      - db
    env_file:
      - .env
    command: php artisan queue:work --queue=default,logs --sleep=3 --tries=3 --timeout=90
    networks:
      - dashboard

  schedule:
    build:
      context: .
      dockerfile: ./docker/production/php-fpm/Dockerfile
      target: production
    container_name: dashboard_schedule
    restart: unless-stopped
    depends_on:
      - db
    env_file:
      - .env
    command: php artisan schedule:work
    networks:
      - dashboard

  db:
    image: mysql:8.0
    container_name: dashboard_db
    env_file:
      - .env
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql
    restart: unless-stopped
    networks:
      - dashboard

networks:
  dashboard:
  proxy-net:
    external: true

volumes:
  db_data:
  storage-production: