services:
  web:
    build:
      context: .
      dockerfile: docker/php/Dockerfile.dev
    container_name: dashboard_web
    working_dir: /var/www/html
    ports:
      - "8000:8000"
    volumes:
      - .:/var/www/html
    command: php artisan serve --host=0.0.0.0 --port=8000
    depends_on:
      - db
    networks:
      - dashboard

  node:
    build:
      context: .
      dockerfile: docker/node/Dockerfile.dev
    container_name: dashboard_node
    working_dir: /var/www/html
    ports:
      - "5173:5173"
    volumes:
      - .:/var/www/html
    command: npm run dev -- --host 0.0.0.0
    depends_on:
      - web
      - db
    networks:
      - dashboard

  db:
    image: mysql:8.0
    container_name: dashboard_db
    env_file:
      - .env
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_HOST: '%'
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./docker/scripts/create-testing-database.sh:/docker-entrypoint-initdb.d/10-create-testing-database.sh
    networks:
      - dashboard

networks:
  dashboard:

volumes:
  db_data:
